// const products = [
//   {
//     id: 1,
//     name: "Fjallraven - Foldsack No. 1 Backpack",
//     href: "#",
//     imageSrc: "https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg",
//     imageAlt: "Fjallraven backpack - Blue",
//     price: "$109.95",
//     color: "Blue",
//   },
//   {
//     id: 2,
//     name: "Mens Casual Premium Slim Fit T-Shirts",
//     href: "#",
//     imageSrc: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
//     imageAlt: "Mens Slim Fit T-Shirt in Gray",
//     price: "$22.3",
//     color: "Gray",
//   },
//   {
//     id: 3,
//     name: "Mens Cotton Jacket",
//     href: "#",
//     imageSrc: "https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg",
//     imageAlt: "Mens Cotton Jacket in Black",
//     price: "$55.99",
//     color: "blue",
//   },
//   {
//     id: 4,
//     name: "Mens Casual Slim Fit",
//     href: "#",
//     imageSrc: "https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg",
//     imageAlt: "Mens Casual Slim Shirt",
//     price: "$15.99",
//     color: "blue",
//   },
//   {
//     id: 5,
//     name: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
//     href: "#",
//     imageSrc: "https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg",
//     imageAlt: "Gold & Silver Dragon Station Bracelet",
//     price: "$695",
//     color: "blue",
//   },
//   {
//     id: 6,
//     name: "Solid Gold Petite Micropave ",
//     href: "#",
//     imageSrc: "https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg",
//     imageAlt: "Petite Micropave Gold Ring",
//     price: "$168",
//     color: "Gold",
//   },
//   {
//     id: 7,
//     name: "White Gold Plated Princess",
//     href: "#",
//     imageSrc: "https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg",
//     imageAlt: "White Gold Plated Ring",
//     price: "$9.99",
//     color: "White Gold",
//   },
//   {
//     id: 8,
//     name: "Pierced Owl Rose Gold Plated Stainless Steel Double",
//     href: "#",
//     imageSrc: "https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg",
//     imageAlt: "Rose Gold Plated Stainless Steel Earring",
//     price: "$10.99",
//     color: "Rose Gold",
//   },
// ];

// export default products;
